language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../Final
  - make -j
  - cd ./bin/
  - ./test_functions --gtest_list_tests
notifications:
  email: false
